name: 'Setup deno'
description: 'Setup Deno and cache dependencies'

runs:
    using: 'composite'
    steps:
        - uses: denoland/setup-deno@v2
        - uses: actions/cache@v4
          with:
              path: |
                  ~/.deno
                  ~/.cache/deno
              key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}
